//@ui5-bundle com/myorg/ui5serverless/Component-preload.js
sap.ui.require.preload({
	"com/myorg/ui5serverless/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","com/myorg/ui5serverless/model/models"],function(e,i,t){"use strict";return e.extend("com.myorg.ui5serverless.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(t.createDeviceModel(),"device")}})});
},
	"com/myorg/ui5serverless/controller/BaseController.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/core/routing/History","sap/ui/core/UIComponent","com/myorg/ui5serverless/model/formatter"],function(e,t,o,r){"use strict";return e.extend("com.myorg.ui5serverless.controller.BaseController",{formatter:r,getModel:function(e){return this.getView().getModel(e)},setModel:function(e,t){return this.getView().setModel(e,t)},getResourceBundle:function(){return this.getOwnerComponent().getModel("i18n").getResourceBundle()},navTo:function(e,t,o){this.getRouter().navTo(e,t,o)},getRouter:function(){return o.getRouterFor(this)},onNavBack:function(){var e=t.getInstance().getPreviousHash();if(e!==undefined){window.history.back()}else{this.getRouter().navTo("appHome",{},true)}}})});
},
	"com/myorg/ui5serverless/controller/MainView.controller.js":function(){sap.ui.define(["com/myorg/ui5serverless/controller/BaseController"],function(e){"use strict";return e.extend("com.myorg.ui5serverless.controller.MainView",{})});
},
	"com/myorg/ui5serverless/i18n/i18n.properties":'title=com.myorg.ui5serverless\nappTitle=com.myorg.ui5serverless\nappDescription=App Description\n',
	"com/myorg/ui5serverless/i18n/i18n_en.properties":'title=com.myorg.ui5serverless\nappTitle=com.myorg.ui5serverless\nappDescription=App Description\n',
	"com/myorg/ui5serverless/manifest.json":'{"_version":"1.21.0","sap.app":{"id":"com.myorg.ui5serverless","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","dataSources":{"mainService":{"uri":"backend/","type":"OData","settings":{"odataVersion":"4.0"}}}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":true,"rootView":{"viewName":"com.myorg.ui5serverless.view.MainView","type":"XML","async":true,"id":"idAppControl"},"dependencies":{"minUI5Version":"1.60.0","libs":{"sap.ui.core":{},"sap.m":{},"sap.ui.layout":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"com.myorg.ui5serverless.i18n.i18n"}},"":{"dataSource":"mainService","settings":{"synchronizationMode":"None","groupId":"$direct","operationMode":"Server","earlyRequests":true},"preload":true}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","viewPath":"com.myorg.ui5serverless.view","controlId":"idAppControl","controlAggregation":"pages","async":true},"routes":[{"name":"RouteMainView","pattern":"RouteMainView","target":["TargetMainView"]}],"targets":{"TargetMainView":{"viewType":"XML","viewLevel":1,"viewId":"idAppControl","viewName":"MainView"}}}}}',
	"com/myorg/ui5serverless/model/formatter.js":function(){sap.ui.define([],function(){"use strict";return{}});
},
	"com/myorg/ui5serverless/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"com/myorg/ui5serverless/view/MainView.view.xml":' <mvc:View controllerName="com.myorg.ui5serverless.controller.MainView"\n  displayBlock="true"\n  xmlns="sap.m"\n  xmlns:mvc="sap.ui.core.mvc"><App id="idAppControl" ><pages><Page title="{i18n>title}"><content><List\n            items="{/People}"\n            headerText="Products"\n            growing="true"\n            growingThreshold="4"\n            growingScrollToLoad="false"><StandardListItem\n              title="{UserName}"\n              description="{Russell}"              \n              iconDensityAware="false"\n              iconInset="false" /></List></content></Page></pages></App></mvc:View>'
});
